### ISSUE TITLE
More than 16 servo motors 

### ISSUE THREAD

**Issue by Neorichi** [sparkfun/Pi_Servo_Hat#4]
Hi,
Thanks for this project but i am interesting about get more than 16 servo motors... could you help me?

Thanks a lot

**Comment by edspark** [comment]
Hello!

This isn't an "issue" in the way Github issues are intended to be used. However, this is a great topic to bring up in the robotics page of our forums: 

https://forum.sparkfun.com/viewforum.php?f=107&sid=6486982292d4ee408e5b5e12ff93be67
